### ISSUE TITLE
TODO Before demo

### ISSUE THREAD

**Issue by dagerikhl** [nvdb-vegdata/datafangst-3d#1]
- [x] Host the application online.
- [x] Test more contracts for undesired behaviour (ie. signs with signpost, do they line up?).
- [x] Get more contracts for testing.
- [x] Dropdown menu to choose between contracts.
- [x] Inquire about sorting of feature collections in Datafangst (is there some logic to the order?).
