### ISSUE TITLE
Potential New features

### ISSUE THREAD

**Issue by dagerikhl** [nvdb-vegdata/datafangst-3d#2]
### TODO

- [ ] Implement GeoData as background map.
- [ ] Add scale-reference for measuring distances in the model.
- [ ] Add description of what the ground level is.

### Done

- [x] Split the ground reference into squares of defined "real world" sizes (e.g. 1x1 meter).
- [x] Make root URL (and potentially all other URLs) serve `index.html` or redirect to `/public/index.html`.
- [x] Indicate loading when system is fetching data (feedback).
- [x] Make public root URL (`/datafangst3d/public/index.html`) serve `index.html` without specifying the file, ie. `/datafangst3d/public`.
- [x] Remove local feature collection files whan hosted and connected to API. No local files will be necessary anymore, we can use the API at `https://datafangst-test.kantega.no/rest/contract/{contractId}/file?destination=NVDB`.
- [x] Fetch sorting order from API `https://www.vegvesen.no/nvdb/api/v2/vegobjekttyper` (can add type id at end for specific type). Add to model and use for sorting `FeatureCollections`.
- [x] Add drawing of filled polygons in addition to linestrings and points.

**Comment by dagerikhl** [comment]
### Drawing of filled polygons

Giving issues as we cannot triangulate (draw faces) on 3D objects, only on 2D. Tried manipulating shapes, seen in code snippet in this comment, but it turns out fairly buggy. Reverting to only showing lines, but keeping this code for future use in `visualization/scene-handler.ts`, should it become relevant.
```
let shape = new THREE.Shape();
shape.moveTo(coordinates[0][0], coordinates[0][2]);
for (let point of coordinates.slice(1)) {
    shape.lineTo(point[0], point[2]);
}
geometry = new THREE.ShapeGeometry(shape);
console.log(coordinates);
console.log(geometry.vertices);
for (let i = 0; i < geometry.vertices.length; i++) {
    geometry.vertices[i].x = coordinates[i][0];
    geometry.vertices[i].y = coordinates[i][1];
    geometry.vertices[i].z = coordinates[i][2];
}
geometry.verticesNeedsUpdate = true;

material = new THREE.MeshBasicMaterial({
    color: color,
    side: THREE.DoubleSide,
    visible: render
});

mesh = new THREE.Mesh(geometry, material);
```
